export default function AiPreventive() {
  return (
    <>
      <section className="section ai-preventive-section">
        <div className="wrap ai-preventive-wrap">
          <div className="ai-preventive-image">
            <img
              alt="AI preventive health water ripple visual"
              src="/assets/ai-preventive-system.png"
            />
          </div>
          <div className="ai-preventive-copy">
            <p className="eyebrow">AI Preventive Health System</p>
            <h2>AI Preventive Health System</h2>
            <p>
              This system captures subtle biological signals generated by the
              body and analyzes them using AI-driven algorithms.
            </p>
            <p>
              By comparing your data against large-scale health reference
              databases, it identifies early functional imbalances across key
              body systems.
            </p>
            <strong>Rather than diagnosing disease, it focuses on:</strong>
            <ul>
              <li>Detecting early deviations from optimal health</li>
              <li>Highlighting potential risks before symptoms appear</li>
              <li>Providing actionable insights for preventive care</li>
            </ul>
            <a className="btn" href="#consultation">
              Talk to Preventive Health AI
            </a>
          </div>
        </div>
      </section>
    </>
  );
}
